import { Metadata } from "next"


// default: Used for pages that don’t have their own title. This acts as the fallback title.
// template: Adds extra text before or after the title on all pages (like a prefix or suffix).
// absolute: Sets a fixed title for a page. It stops the layout from changing or adding to the title using the template.

export const metadata = {
  title:{
    default:"Next js-CodeEvolution",
    template:"%s | CodeEvolution",
    
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightblue",padding:"1rem"}}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{backgroundColor:"pink",padding:"1rem"}}>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
